global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['api:8000']  # 'api' is your FastAPI service name
    scrape_interval: 5s
    metrics_path: '/metrics'